"use client";

import { AlertCircle, ArrowLeft, Ban, Check, CircleX, CreditCard, LoaderCircle, Printer, RefreshCw, Search, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useParams, usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { humanize } from "@/lib/api-data";
import { ArchMark } from "@/components/brand/arch-mark";
import { PageHeader } from "@/components/page-header";
import { api, apiErrorMessage } from "@/lib/api";
import { asRecord, formatDate, formatMoney, readNumber, readText, unwrapPayload, type ApiRecord } from "@/lib/api-data";
import { BRAND } from "@/lib/brand";

function findValue(value: unknown, keys: string[]): string | undefined {
  if (!value || typeof value !== "object") return undefined;
  if (Array.isArray(value)) {
    for (const child of value) {
      const found = findValue(child, keys);
      if (found) return found;
    }
    return undefined;
  }
  const record = value as ApiRecord;
  for (const [key, child] of Object.entries(record)) if (keys.includes(key.toLowerCase()) && typeof child === "string" && child.trim()) return child;
  for (const child of Object.values(record)) {
    const found = findValue(child, keys);
    if (found) return found;
  }
  return undefined;
}

function isPaid(status: string) {
  return ["paid", "completed", "success"].includes(status.toLowerCase());
}

function isCancelled(status: string) {
  return ["cancelled", "canceled", "cancel"].includes(status.toLowerCase());
}

function isFailed(status: string) {
  return ["failed", "failure", "error"].includes(status.toLowerCase());
}

function PaymentDetails({ payment }: { payment: ApiRecord }) {
  const fee = asRecord(payment.fee) ?? {};
  const semester = asRecord(fee.semester) ?? asRecord(payment.semester) ?? {};
  const student = asRecord(payment.student) ?? {};
  const user = asRecord(payment.user) ?? asRecord(student.user) ?? student;
  const amount = readNumber(payment, "amount") ?? readNumber(fee, "amount");
  const method = readText(payment, "method") ?? "bKash";
  const date = readText(payment, "paidAt") ?? readText(payment, "updatedAt") ?? readText(payment, "createdAt");
  const transaction = readText(payment, "transactionId") ?? readText(payment, "trxID") ?? readText(payment, "bkashTransactionId");
  const status = readText(payment, "status") ?? "—";
  const id = readText(payment, "id") ?? readText(payment, "paymentId") ?? "—";
  const fields: [string, string][] = [
    ["Receipt for", readText(user, "name") ?? readText(payment, "studentName") ?? "Student"],
    ["Fee", readText(fee, "title") ?? readText(fee, "feeType") ?? "Semester fee"],
    ["Semester", readText(semester, "name") ?? "—"],
    ["Amount", amount !== undefined ? formatMoney(amount) : "—"],
    ["Method", method],
    ["Transaction ID", transaction ?? "—"],
    ["Paid on", date ? formatDate(date) : "—"],
    ["Status", humanize(status)],
    ["Payment ID", id],
  ];
  return <dl className="receipt-fields">{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{label === "Method" ? <span className="bkash-chip">{value}</span> : value}</dd></div>)}</dl>;
}

function ReceiptDocument({ payment }: { payment: ApiRecord }) {
  const id = readText(payment, "id") ?? readText(payment, "paymentId") ?? "—";
  return <article className="receipt-paper paper"><header className="receipt-header"><ArchMark /><div><h2>Payment receipt</h2><p>{BRAND.name}</p></div></header><PaymentDetails payment={payment} /><footer className="receipt-footer">Receipt ID: {id}<span>Generated by {BRAND.name}</span></footer></article>;
}

function PrintActions({ backHref }: { backHref: string }) {
  return <div className="receipt-toolbar no-print"><Link className="button button-ghost" href={backHref}><ArrowLeft size={17} />Back</Link><button className="button button-secondary" onClick={() => window.print()}><Printer size={17} />Print receipt</button></div>;
}

function ReceiptView({ paymentId, mode }: { paymentId: string; mode: "student" | "admin" }) {
  const [payment, setPayment] = useState<ApiRecord>();
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [retry, setRetry] = useState(0);
  useEffect(() => {
    let active = true;
    setLoading(true);
    setError("");
    api.get<unknown>(`/payments/${encodeURIComponent(paymentId)}`).then(({ data }) => {
      if (active) setPayment(asRecord(unwrapPayload(data)));
    }).catch((reason: unknown) => { if (active) setError(apiErrorMessage(reason, "Couldn’t load payment receipt. Check the payment ID and try again.")); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [paymentId, retry]);

  const backHref = mode === "student" ? "/student/fees" : "/admin/payments";
  if (loading) return <div className="payment-loading"><div className="payment-arch"><span /><LoaderCircle className="spinner" size={20} /></div><h1>Loading receipt…</h1><div className="receipt-skeleton"><span /><span /><span /><span /></div></div>;
  if (error || !payment) return <section className="payment-error" role="alert"><div className="payment-state-icon danger-state"><AlertCircle size={24} /></div><h1>We couldn’t find that payment</h1><p>{error || "No payment details were returned. Check the payment ID and try again."}</p><div className="header-button-group"><button className="button button-secondary" onClick={() => setRetry((count) => count + 1)}>Try again</button><Link className="button button-primary" href={backHref}>Back to {mode === "student" ? "fees" : "payments"}</Link></div></section>;

  return <div className="receipt-view"><PrintActions backHref={backHref} /><ReceiptDocument payment={payment} /></div>;
}

export function StudentPaymentReceipt() {
  const params = useParams<{ paymentId: string }>();
  return <><PageHeader title="Payment receipt" description="Verified payment details from the university API." /><ReceiptView paymentId={params.paymentId} mode="student" /></>;
}

const paymentLookupSchema = z.object({ paymentId: z.string().trim().min(1, "Enter a payment ID.") });
type PaymentLookup = z.infer<typeof paymentLookupSchema>;

export function AdminPaymentLookup() {
  const [paymentId, setPaymentId] = useState("");
  const form = useForm<PaymentLookup>({ resolver: zodResolver(paymentLookupSchema), mode: "onTouched" });
  function submit(values: PaymentLookup) { setPaymentId(values.paymentId); }
  return <><PageHeader title="Payments" description="Find a payment receipt by its ID." /><section className="form-panel payment-lookup-panel"><form className="lookup-form" onSubmit={form.handleSubmit(submit)}><div className="field-group"><label className="field-label" htmlFor="paymentId">Payment ID</label><input id="paymentId" className="field-control" placeholder="Paste payment ID" {...form.register("paymentId")} />{form.formState.errors.paymentId?.message && <p className="field-error"><AlertCircle size={16} />{form.formState.errors.paymentId.message}</p>}</div><button className="button button-primary" type="submit"><Search size={17} />Find payment</button></form></section>{paymentId && <ReceiptView paymentId={paymentId} mode="admin" />}</>;
}

export function PaymentLanding() {
  const params = useSearchParams();
  const pathname = usePathname();
  const paymentId = params.get("paymentID") ?? params.get("paymentId") ?? "";
  const urlStatus = (params.get("status") ?? "").toLowerCase();
  const [payment, setPayment] = useState<ApiRecord>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [refresh, setRefresh] = useState(0);
  const [pollCount, setPollCount] = useState(0);
  const [timedOut, setTimedOut] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (!paymentId) { setLoading(false); setError("Payment ID is missing from the return link."); return; }
    let active = true;
    setLoading(true);
    setError("");
    api.get<unknown>(`/payments/${encodeURIComponent(paymentId)}`).then(({ data }) => {
      if (active) setPayment(asRecord(unwrapPayload(data)));
    }).catch((reason: unknown) => {
      if (!active) return;
      const status = typeof reason === "object" && reason !== null && "response" in reason ? (reason as { response?: { status?: number } }).response?.status : undefined;
      setError(status === 401 ? "Sign in to view this payment." : apiErrorMessage(reason, "Couldn’t verify the payment. Try again."));
    }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [paymentId, refresh]);

  const apiStatus = (readText(payment ?? {}, "status") ?? "").toLowerCase();
  const terminal = isPaid(apiStatus) || isCancelled(apiStatus) || isFailed(apiStatus);
  useEffect(() => {
    if (!paymentId || !payment || terminal || pollCount >= 5) return;
    const timer = window.setTimeout(() => { setPollCount((count) => count + 1); setRefresh((count) => count + 1); }, 4000);
    return () => window.clearTimeout(timer);
  }, [paymentId, payment, terminal, pollCount]);

  useEffect(() => {
    const timer = window.setTimeout(() => setTimedOut(true), 15000);
    return () => window.clearTimeout(timer);
  }, []);

  if (loading && !payment) return <PaymentStateShell><div className="payment-arch is-drawing"><span /><LoaderCircle className="spinner" size={22} /></div><h1>Confirming your payment…</h1><p className="payment-state-subtitle">We’re checking the status with the university API.</p><div className="receipt-skeleton"><span /><span /><span /></div></PaymentStateShell>;

  if (error) return <PaymentStateShell><div className="payment-state-icon danger-state"><AlertCircle size={24} /></div><h1>{paymentId ? "Payment status unavailable" : "We couldn’t find that payment"}</h1><p>{error}</p><div className="header-button-group">{paymentId && !error.includes("Sign in") && <button className="button button-secondary" onClick={() => setRefresh((count) => count + 1)}>Refresh status</button>}{error.includes("Sign in") ? <Link className="button button-primary" href={`/login?next=${encodeURIComponent(pathname + window.location.search)}`}>Sign in to view payment</Link> : <Link className="button button-primary" href="/student/fees">Back to fees</Link>}</div></PaymentStateShell>;

  if (!payment) return <PaymentStateShell><div className="payment-state-icon danger-state"><AlertCircle size={24} /></div><h1>We couldn’t find that payment</h1><p>The API did not return a payment record for this ID.</p><Link className="button button-primary" href="/student/fees">Back to fees</Link></PaymentStateShell>;

  if (isPaid(apiStatus)) return <PaymentStateShell><div className="payment-arch success-state"><span /><Check size={35} /></div><p className="section-kicker payment-kicker">Payment confirmed</p><h1>Payment received</h1><p className="payment-state-subtitle">Your payment is recorded by the university.</p><div className="payment-summary"><PaymentDetails payment={payment} /></div><div className="header-button-group payment-actions"><Link className="button button-primary" href={`/student/payments/${encodeURIComponent(paymentId)}`}>View receipt</Link><Link className="button button-secondary" href="/student/fees">Go to fees</Link></div></PaymentStateShell>;

  if (isCancelled(apiStatus) || urlStatus === "cancel" && isCancelled(apiStatus)) return <PaymentStateShell><div className="payment-state-icon neutral-state"><Ban size={24} /></div><h1>Payment cancelled</h1><p className="payment-state-subtitle">You weren’t charged. Your fee is still unpaid.</p><div className="header-button-group"><Link className="button button-primary" href="/student/fees">Go to fees</Link></div></PaymentStateShell>;

  if (isFailed(apiStatus)) return <PaymentStateShell><div className="payment-state-icon danger-state"><CircleX size={24} /></div><h1>Payment didn’t go through</h1><p className="payment-state-subtitle">{readText(payment, "failureReason") ?? readText(payment, "message") ?? "The API marked this payment as failed."}</p><div className="payment-support">Need help? <a href={`mailto:${BRAND.supportEmail}`}>{BRAND.supportEmail}</a></div><Link className="button button-primary" href="/student/fees">Try again</Link></PaymentStateShell>;

  return <PaymentStateShell><div className="payment-arch is-drawing"><span /><LoaderCircle className="spinner" size={22} /></div><h1>{timedOut ? "Still confirming" : "Confirming your payment…"}</h1><p className="payment-state-subtitle">{timedOut ? "Check your fees in a minute. Your status will continue to update here." : "We’re waiting for bKash to confirm the transaction."}</p><div className="inline-alert info-alert"><ShieldCheck size={18} /><span>{urlStatus === "success" ? "The return link says success, but the API has not confirmed payment yet." : `Current API status: ${apiStatus || "pending"}.`}</span></div><div className="header-button-group"><button className="button button-secondary" onClick={() => setRefresh((count) => count + 1)}><RefreshCw size={16} />Refresh status</button><Link className="button button-primary" href="/student/fees">Check fees</Link></div></PaymentStateShell>;
}

function PaymentStateShell({ children }: { children: React.ReactNode }) {
  return <main id="main-content" className="payment-page"><section className="payment-card"><Link href="/" className="payment-brand"><ArchMark /></Link>{children}</section></main>;
}